### ISSUE TITLE
Client does not support authentication protocol requested by server; consider upgrading MySQL client

### ISSUE THREAD

**Issue by michaelpalumbo** [RekhaLeelara/WhatTheHealth#4]
```shell
sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators node_modules/sequelize/lib/sequelize.js:245:13
Server listening on: http://localhost:3001
This error occured ConnectionError [SequelizeConnectionError]: Client does not support authentication protocol requested by server; consider upgrading MySQL client
    at /Users/michaelpalumbo/_ut-bootcamp/WhatTheHealth/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:149:19
    at tryCatcher (/Users/michaelpalumbo/_ut-bootcamp/WhatTheHealth/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/michaelpalumbo/_ut-bootcamp/WhatTheHealth/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/michaelpalumbo/_ut-bootcamp/WhatTheHealth/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/michaelpalumbo/_ut-bootcamp/WhatTheHealth/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/michaelpalumbo/_ut-bootcamp/WhatTheHealth/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/Users/michaelpalumbo/_ut-bootcamp/WhatTheHealth/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/michaelpalumbo/_ut-bootcamp/WhatTheHealth/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/michaelpalumbo/_ut-bootcamp/WhatTheHealth/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/michaelpalumbo/_ut-bootcamp/WhatTheHealth/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:462:21) {
  parent: Error: Client does not support authentication protocol requested by server; consider upgrading MySQL client
      at Packet.asError (/Users/michaelpalumbo/_ut-bootcamp/WhatTheHealth/node_modules/mysql2/lib/packets/packet.js:708:17)
      at ClientHandshake.execute (/Users/michaelpalumbo/_ut-bootcamp/WhatTheHealth/node_modules/mysql2/lib/commands/command.js:28:26)
      at Connection.handlePacket (/Users/michaelpalumbo/_ut-bootcamp/WhatTheHealth/node_modules/mysql2/lib/connection.js:408:32)
      at PacketParser.onPacket (/Users/michaelpalumbo/_ut-bootcamp/WhatTheHealth/node_modules/mysql2/lib/connection.js:70:12)
      at PacketParser.executeStart (/Users/michaelpalumbo/_ut-bootcamp/WhatTheHealth/node_modules/mysql2/lib/packet_parser.js:75:16)
      at Socket.<anonymous> (/Users/michaelpalumbo/_ut-bootcamp/WhatTheHealth/node_modules/mysql2/lib/connection.js:77:25)
      at Socket.emit (events.js:376:20)
      at addChunk (internal/streams/readable.js:309:12)
      at readableAddChunk (internal/streams/readable.js:284:9)
      at Socket.Readable.push (internal/streams/readable.js:223:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
    code: 'ER_NOT_SUPPORTED_AUTH_MODE',
    errno: 1251,
    sqlState: '08004',
    sqlMessage: 'Client does not support authentication protocol requested by server; consider upgrading MySQL client'
  },
  original: Error: Client does not support authentication protocol requested by server; consider upgrading MySQL client
      at Packet.asError (/Users/michaelpalumbo/_ut-bootcamp/WhatTheHealth/node_modules/mysql2/lib/packets/packet.js:708:17)
      at ClientHandshake.execute (/Users/michaelpalumbo/_ut-bootcamp/WhatTheHealth/node_modules/mysql2/lib/commands/command.js:28:26)
      at Connection.handlePacket (/Users/michaelpalumbo/_ut-bootcamp/WhatTheHealth/node_modules/mysql2/lib/connection.js:408:32)
      at PacketParser.onPacket (/Users/michaelpalumbo/_ut-bootcamp/WhatTheHealth/node_modules/mysql2/lib/connection.js:70:12)
      at PacketParser.executeStart (/Users/michaelpalumbo/_ut-bootcamp/WhatTheHealth/node_modules/mysql2/lib/packet_parser.js:75:16)
      at Socket.<anonymous> (/Users/michaelpalumbo/_ut-bootcamp/WhatTheHealth/node_modules/mysql2/lib/connection.js:77:25)
      at Socket.emit (events.js:376:20)
      at addChunk (internal/streams/readable.js:309:12)
      at readableAddChunk (internal/streams/readable.js:284:9)
      at Socket.Readable.push (internal/streams/readable.js:223:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
    code: 'ER_NOT_SUPPORTED_AUTH_MODE',
    errno: 1251,
    sqlState: '08004',
    sqlMessage: 'Client does not support authentication protocol requested by server; consider upgrading MySQL client'
  }
}
```

**Comment by michaelpalumbo** [comment]
solved. The top-voted solution is what worked for me: https://stackoverflow.com/questions/50093144/mysql-8-0-client-does-not-support-authentication-protocol-requested-by-server
